// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO-P1MzcOaiUUfxqjbYYRZ8OSl4WMtLMg',
    appId: '1:509095096022:web:25c2a20e43d6973f456377',
    messagingSenderId: '509095096022',
    projectId: 'inclass17-35ecb',
    authDomain: 'inclass17-35ecb.firebaseapp.com',
    storageBucket: 'inclass17-35ecb.firebasestorage.app',
    measurementId: 'G-WW6BEW0R9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6P7a3rUP3w7ocVuzeFzT8XuNC5LP2jp8',
    appId: '1:509095096022:android:b6c4ad8848507020456377',
    messagingSenderId: '509095096022',
    projectId: 'inclass17-35ecb',
    storageBucket: 'inclass17-35ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHV9UdFuZVyC9m_Qz3sZRhwp1XSuayFZ8',
    appId: '1:509095096022:ios:1c338bfdd2e826d6456377',
    messagingSenderId: '509095096022',
    projectId: 'inclass17-35ecb',
    storageBucket: 'inclass17-35ecb.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHV9UdFuZVyC9m_Qz3sZRhwp1XSuayFZ8',
    appId: '1:509095096022:ios:1c338bfdd2e826d6456377',
    messagingSenderId: '509095096022',
    projectId: 'inclass17-35ecb',
    storageBucket: 'inclass17-35ecb.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO-P1MzcOaiUUfxqjbYYRZ8OSl4WMtLMg',
    appId: '1:509095096022:web:6a45be9a04e5fbbc456377',
    messagingSenderId: '509095096022',
    projectId: 'inclass17-35ecb',
    authDomain: 'inclass17-35ecb.firebaseapp.com',
    storageBucket: 'inclass17-35ecb.firebasestorage.app',
    measurementId: 'G-ZSKLVJQK5Y',
  );
}
